# Generated by Django 3.2.7 on 2021-11-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='work_group',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
