# Generated by Django 3.2.7 on 2021-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('หัวหน้างาน', 'หัวหน้างาน'), ('พนักงาน', 'พนักงาน'), ('ผู้ดูแล', 'ผู้ดูแล')], max_length=30),
        ),
    ]
