# Generated by Django 3.2.7 on 2021-11-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistories',
            options={'ordering': ['-plan__datetime_start']},
        ),
    ]
