# Generated by Django 3.2.7 on 2021-11-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_userhistories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplans',
            options={'ordering': ['datetime_start']},
        ),
        migrations.AlterField(
            model_name='userhistories',
            name='ot_hour',
            field=models.FloatField(default=0.0),
        ),
    ]
