# Generated by Django 3.2.7 on 2021-11-17 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211117_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbranchs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users'),
        ),
    ]
