# Generated by Django 3.2.7 on 2021-11-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_workbranchs_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['roles']},
        ),
    ]
